### PR TITLE
Added postgresql db support to telemetry

### PR DESCRIPTION
**Pull request by bplower**
I've added postgresql database support for telemetry, using PDO similar to the way sqlite3 support was implemented. I moved all database related settings into a separate file so people don't have to modify telemetry.php in order to get everything set up. Updated related documentation.

### CODE REVIEW

**Comment by adolfintel** [comment]
Nice, thank you

**Comment by adolfintel** [comment]
I assume telemetry.sql works with postgresql as well?

**Comment by bplower** [comment]
It doesn't actually, I had to tweak the schema slightly to get it to work. I'll make an export of the working schema and open another PR when it's ready

**Comment by adolfintel** [comment]
Ok, please do it ASAP because I've already merged your PR and I don't want to leave a feature semi-broken.

**Pull request merged**
