### PR TITLE
Added Telemetry History Support

### PR DESCRIPTION
**Pull request by lesteff**
Just a simple Telemetry History addon with json data. There is a view for regular users and admins (via IP-Range detection/limitation). 

At the moment limited to mysql and very brief implementation with jquery.

Lete me know what you think.

### CODE REVIEW

**Comment by adolfintel** [comment]
Potentially this is very useful, but it needs some sort of authentication instead of just checking the IP, which is often dynamic (password or hash in the PHP file or hash in the DB), as well as support for other databases and some documentation.
If you have time to do it, of course.

**Comment by schi-svetlin** [comment]
I tried to look, but for some reason the history is not displayed.
Although made changes to the administrator in telemetry_history.php
And where to get the file structure ip_in_range.php

**Comment by lesteff** [comment]
Hi. ip_in_range.php is a library by [CloudFlare](https://github.com/cloudflare/CloudFlare-Tools/blob/master/cloudflare/ip_in_range.php) sorry I missed that. 

Actually authentication can do by "whatever-somebody-has". If not authenticated, history of the requesting IP were deliverd. In our case our ISP Admin IP Range is authenticated enought. Maybe I can do another sample with static token. 

@adolfintel I don't have a PostgreSQL/Lite installation - hopfully somebody else can submit a sample?

Actually we are very happy with your speedtest and the history extension.

**Comment by adolfintel** [comment]
@lesteff I don't have a Postgre or SQLite install either, they were all PRs from other users.

**Comment by schi-svetlin** [comment]
the server is running on nginx +php-frem, msql
In the base I see logs, but the history is not displayed on the HTML.

**Comment by lesteff** [comment]
why not merge? It does not conflict in any way. Like the other examples in your repo, this would be another puzzle who someone can adapt.

**Pull request closed without merging**
