### PR TITLE
Additional features and restructured PHP examples using Docker recipes

### PR DESCRIPTION
**Pull request by tnsantana**
- Multiple points of test with automatic selection of lowest latency servers
- REST method example for servers list and report results
- Packet loss counter for ping tests instead of flow abortion
- Geolocation and ISP data from http://ipinfo.io
- Beautiful URLs and compatibility with simple server setup for static files
- NGINX Docker recipe example with CORS enabled config
- Apache/PHP Docker recipe example with rewrite rules examples
- Documentation update for new parameters and result events

### CODE REVIEW

**Comment by tnsantana** [comment]
Let me know what you think about distribute Docker recipes for test servers setup. We can add an example for Node.js.

**Comment by adolfintel** [comment]
Wow, thank you very much for all these improvements.
I'll have to test them in the next few days, then I'll merge it

**Comment by adolfintel** [comment]
I'm taking a look at your code and there are a few things that need a bit of clarification:
* Multiple points of test: I can't contact another server directly with XHR, because Cross-domain requests are blocked by all browsers, so it would only work within your domain. How did you plan to use it? 
Here's a possible alternative solution, although it's a bit harder to implement:
-Run the test from inside an invisible iframe
-Have a script load iframes from a multiple points of test and use the onload event to determine which one loaded faster
-Use that server to run the actual speedtest and read the results from the invisible iframe
* Packet loss: measuring how many pings got lost is not an accurate mesaurement of packet loss because we are over TCP, which has retransmission. A ping will only get lost if the server is overloaded or if the connection is so slow that it triggers a timeout (or the user disconnected the network).
* Lastly, the docker files. I assume they are right because I never used docker. Can you provide some documentation on how they work and how to install them?

Thank you ;)

**Comment by tnsantana** [comment]
Sure, answering in the same sequence:
- Cross-Origin Resource Sharing: There is no need for any kludge using iframes. I've mentioned in the pull request and revisions related with this subject, a CORS enabled example for NGINX with the Docker recipe. You can use any server if you set the proper HTTP headers (Access-Control-Allow-Origin). Take a look at nginx_static/conf/point_of_test.conf
- Packet loss: Correct. And it is not a real ping test since we're working with very limited resources/instructions in a browser. We can rename it to pingFailures or whatever if you prefer. The idea is an availability test from client perspective (acceptable responsiveness). Your question reminded me about the xhr timeout, i forgot to add a parameter for it.
- Docker: Please see the comments on top of the Dockerfiles, if you decide to adopt it we can work in a more detailed and visible description.

Very short and straightforward example, considering a Debian based Linux distro:
apt-get update
apt-get install docker.io
cd speedtest/nginx_static
docker build -t anyName .
docker run -d -p8080:80 anyName

-d, --detach                                Run container in background and print container ID
-p, --publish list                          Publish a container's port(s) to the host (default [])

If you're using any other OS, it's very well documented:
https://www.docker.com/community-edition#/download
https://docs.docker.com/get-started/

Thanks

**Comment by adolfintel** [comment]
Oh ok, sorry I totally missed the CORS headers.

Here's what I'll do then before I merge your PR:
* Separate the docker files and put them in a separate project, because I prefer a manual installation for this
* Put the CORS headers in a php file that will be imported by all examples, so that conf file is not needed
* Update the documentation to explain that the ping and packet loss tests are not very accurate

Meanwhile, if you have time, write a readme.md that explains how to install the speedtest using docker.

**Comment by tnsantana** [comment]
No problem.

Actually the conf example for apache is not for CORS, it's an example to allow directory specific configurations (overrride config using .htaccess files). This is used for beautiful URLs like /download/chunkSize.

I just suggested Docker to keep reproducible environments, easy to follow recipes and to avoid doubts about server-side.

These changes might be too specific, so i suggest to close this pull request and discuss in more details how we can contribute considering your plans, without my assumptions.

Let's close this pull request and discuss about a separate branch with less invasive structural changes. 

What do you think?

Thank you

**Comment by adolfintel** [comment]
Yea, you could make a pull request with
* ISP detection, etc
* Multiple points of test
* Packet loss test
* Documentation changes

The docker stuff may be a bit specific so I'll release it as a separate project. And also the telemetry you've added may be a bit too specific so maybe I could make a dedicated branch for it.

If that looks good, I'll close the PR so you can make them separately, ok?

**Comment by tnsantana** [comment]
Yes, let's use a separate branch.

**Comment by adolfintel** [comment]
I created a testing branch, you can send the first PR to master and the second PR to testing, when you want.

**Pull request closed without merging**
