### PR TITLE
cloudflare cache-control

### PR DESCRIPTION
**Pull request by mathieu-aubin**
proxy/cloudflare cache control

### CODE REVIEW

**Comment by adolfintel** [comment]
Superseded by c3e576ddba3dd59e1741458a89eaf53941bf4cac

**Comment by mathieu-aubin** [comment]
its one way to somewhat avoid merging pull requests. Its become popular to take pull requests and add to own commits.

**Comment by adolfintel** [comment]
I'm sorry, I know this probably looks rude, but what happened is that you sent in your PR while I was in the middle of a project restructuring and update that included adding those same headers (the problem was reported via email a few weeks ago), and that's why I didn't merge it.
I assure you that I don't make it a habit of stealing code from PRs and making it my own, if you look back in the project's history, a lot of small PRs like this one were accepted.
It was just bad timing, sorry.

**Comment by mathieu-aubin** [comment]
No worries, i know it sounded accusatory but it wasn't the direct intention. I did look, yes. It's happenned to me countless times in the past few months and even if there nothing close to glory in contributing to open source projects, i always felt that recognition was due in the same way as we mention the use of open source libraries/code in our projects. This whole mindset i got in when seeing this would most likely have been avoided with a simple 'thanks' of some sort. Altho i wasnt disrespectful in my comment, i apologize for it.

**Pull request closed without merging**
